import { NextRequest, NextResponse } from "next/server";
import crypto from "crypto";
import { prisma } from "@/lib/prisma";
import { requireApiRoles, apiAuthErrorResponse } from "@/lib/api-auth";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type RouteContext = { params: Promise<{ id: string }> };

/**
 * Admin-only: generates a one-time password reset link for a user, to be
 * handed to them in person / by message. This replaced the public
 * /api/auth/forgot-password endpoint, which returned a working reset link to
 * anyone who typed a username (so anyone could take over any account,
 * including Admin). The link is valid for 1 hour and can be used once; the
 * reset itself is still done on /reset-password via /api/auth/reset-password.
 */
export async function POST(req: NextRequest, { params }: RouteContext) {
  let session;
  try {
    session = await requireApiRoles(["Admin"]);
  } catch (e) {
    const authError = apiAuthErrorResponse(e);
    if (authError) return authError;
    throw e;
  }

  const { id } = await params;
  const userId = Number(id);
  if (!Number.isInteger(userId) || userId < 1) {
    return NextResponse.json({ error: "The user account no longer exists." }, { status: 400 });
  }

  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const result = await prisma.$transaction(async (tx: any) => {
      const user = await tx.user.findFirst({ where: { id: userId, deletedAt: null } });
      if (!user) throw new Error("The user account no longer exists.");
      if (!user.isActive) throw new Error("Reactivate this account before generating a reset link.");

      // Expire any outstanding links for this user first.
      await tx.passwordResetToken.updateMany({
        where: { userId: user.id, used: false },
        data: { used: true },
      });

      const rawToken = crypto.randomBytes(32).toString("hex"); // 64 hex chars
      const expiresAt = new Date(Date.now() + 60 * 60 * 1000); // 1 hour
      await tx.passwordResetToken.create({ data: { userId: user.id, token: rawToken, expiresAt } });

      await tx.auditLog.create({
        data: {
          performedBy: session.userId,
          actionType: "password_reset_link_generated",
          recordType: "user",
          recordId: user.id,
          recordReference: user.username,
          actionDetails: { user_id: user.id, username: user.username, role: user.role },
          reason: "Password reset link generated by an administrator.",
          ipAddress: req.headers.get("x-forwarded-for") ?? "unknown",
        },
      });

      return { rawToken, fullName: user.fullName };
    });

    const proto = req.headers.get("x-forwarded-proto") ?? req.nextUrl.protocol.replace(":", "");
    const host = req.headers.get("x-forwarded-host") ?? req.headers.get("host") ?? req.nextUrl.host;
    const resetLink = `${proto}://${host}/reset-password?token=${result.rawToken}`;

    return NextResponse.json({ ok: true, fullName: result.fullName, resetLink });
  } catch (err) {
    const message = err instanceof Error ? err.message : "The reset link could not be generated.";
    return NextResponse.json({ error: message }, { status: 400 });
  }
}
